#!/usr/bin/php
<?php

error_reporting(E_ALL);
ini_set('display_errors', '1');

if (PHP_SAPI != 'cli') {
    echo PHP_EOL . 'Run on CLI only!' . PHP_EOL . PHP_EOL;
    exit(1);
}

require __DIR__ . '/vendor/autoload.php';

function usage() {
    global $argv;
    echo "[ERROR] Please provide two PDF files!" . PHP_EOL . 
         "Usage: " . $argv[0] . " file1.pdf file2.pdf" . PHP_EOL . PHP_EOL;
}

if ($argc != 3) {
    usage();
    exit(1);
} else {
    $file1 = $argv[1];
    $file2 = $argv[2];

    if (file_exists($file1)) {
        if (file_exists($file2)) {
            $pdf = new \Jurosh\PDFMerge\PDFMerger;
            $pdf->addPDF($file1, 'all', 'vertical')
                ->addPDF($file2, 'all', 'vertical');
            $pdf->merge('file', 'combined.pdf');
        } else {
            echo "[ERROR] The file '" . $file2 . "' could not be found!" . PHP_EOL;
        }
    } else {
        echo "[ERROR] The file '" . $file1 . "' could not be found!" . PHP_EOL;
    }
}